/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AsyncComponent: typeof import('./src/components/AsyncComponent.vue')['default']
    Basic: typeof import('./src/components/ssrComponents/Basic.vue')['default']
    BgAttachment: typeof import('./src/components/bgAttachment/index.vue')['default']
    Carousel: typeof import('./src/components/Carousel/index.vue')['default']
    CarouselDot: typeof import('./src/components/Carousel/CarouselDot.vue')['default']
    CarouselItem: typeof import('./src/components/Carousel/CarouselItem.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Drag: typeof import('./src/components/Drag/index.vue')['default']
    Fireworks: typeof import('./src/components/Fireworks/index.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Modal: typeof import('./src/components/Modal/index.vue')['default']
    Overlayer: typeof import('./src/components/Overlayer/index.vue')['default']
    Popover: typeof import('./src/components/Popover/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheImage: typeof import('./src/components/starPort/TheImage.vue')['default']
    VirtualList: typeof import('./src/components/VirtualList/index.vue')['default']
    VirtualListItem: typeof import('./src/components/VirtualList/VirtualListItem.vue')['default']
    WaterfallFlow: typeof import('./src/components/WaterfallFlow/index.vue')['default']
    WaterfallFlowItem: typeof import('./src/components/WaterfallFlow/waterfallFlowItem.vue')['default']
  }
}
