/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AliveKeep: typeof import('./../src/components/AliveKeep.vue')['default']
    ArrowIcon: typeof import('./../src/components/ArrowIcon.vue')['default']
    AsyncComponent: typeof import('./../src/components/AsyncComponent.vue')['default']
    CanvasDraw: typeof import('./../src/components/CanvasDraw/index.vue')['default']
    CanvasTool: typeof import('./../src/components/CanvasDraw/CanvasTool.vue')['default']
    CodeEditor: typeof import('./../src/components/CodeEditor/CodeEditor.vue')['default']
    CodeEditorContent: typeof import('./../src/components/CodeEditor/CodeEditorContent.vue')['default']
    CodeLinePrism: typeof import('./../src/components/CodeLinePrism.vue')['default']
    CosmicStars: typeof import('./../src/components/PageBackground/CosmicStars.vue')['default']
    Counter: typeof import('./../src/components/Counter.vue')['default']
    CssVirtualList: typeof import('./../src/components/VirtualList/CssVirtualList.vue')['default']
    DemochallengeList: typeof import('./../src/components/DemochallengeList.vue')['default']
    DHeader: typeof import('./../src/components/DivTable/DHeader.vue')['default']
    EditorDiv: typeof import('./../src/components/EditorDiv.vue')['default']
    Fireworks: typeof import('./../src/components/Fireworks/index.vue')['default']
    Footer: typeof import('./../src/components/Footer.vue')['default']
    InputAnimate: typeof import('./../src/components/InputAnimate/index.vue')['default']
    Loading: typeof import('./../src/components/Loading.vue')['default']
    MineBlock: typeof import('./../src/components/Minesweeper/MineBlock.vue')['default']
    Minesweeper: typeof import('./../src/components/Minesweeper/index.vue')['default']
    Modal: typeof import('./../src/components/Modal/index.vue')['default']
    Overlayer: typeof import('./../src/components/Overlayer/index.vue')['default']
    PageBackground: typeof import('./../src/components/PageBackground/index.vue')['default']
    Popover: typeof import('./../src/components/Popover/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('./../src/components/Starport/starport.vue')['default']
    StarportCarrier: typeof import('./../src/components/Starport/starportCarrier.vue')['default']
    StarportCraft: typeof import('./../src/components/Starport/starportCraft.vue')['default']
    TextFallenStreet: typeof import('./../src/components/TextFallenStreet.vue')['default']
    'TextFallenStreet-Undetermined': typeof import('./../src/components/TextFallenStreet--undetermined.vue')['default']
    THeader: typeof import('./../src/components/Table/THeader.vue')['default']
    TheImage: typeof import('./../src/components/TheImage.vue')['default']
    Treelist: typeof import('./../src/components/Treelist/index.vue')['default']
    TreeListItem: typeof import('./../src/components/Treelist/TreeListItem.vue')['default']
    Tsparticles: typeof import('./../src/components/PageBackground/Tsparticles.vue')['default']
    VirtualList: typeof import('./../src/components/VirtualList/index.vue')['default']
    VirtualListItem: typeof import('./../src/components/VirtualList/VirtualListItem.vue')['default']
    WaterfallFlow: typeof import('./../src/components/WaterfallFlow.vue')['default']
  }
}
