/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/blog/': RouteRecordInfo<'/blog/', '/blog', Record<never, never>, Record<never, never>>,
    '/demoChallenge/': RouteRecordInfo<'/demoChallenge/', '/demoChallenge', Record<never, never>, Record<never, never>>,
    '/demoChallenge/autoNavBar': RouteRecordInfo<'/demoChallenge/autoNavBar', '/demoChallenge/autoNavBar', Record<never, never>, Record<never, never>>,
    '/demoChallenge/canvasDrawPage': RouteRecordInfo<'/demoChallenge/canvasDrawPage', '/demoChallenge/canvasDrawPage', Record<never, never>, Record<never, never>>,
    '/demoChallenge/canvasPlum': RouteRecordInfo<'/demoChallenge/canvasPlum', '/demoChallenge/canvasPlum', Record<never, never>, Record<never, never>>,
    '/demoChallenge/digitalRain': RouteRecordInfo<'/demoChallenge/digitalRain', '/demoChallenge/digitalRain', Record<never, never>, Record<never, never>>,
    '/demoChallenge/editorDiv': RouteRecordInfo<'/demoChallenge/editorDiv', '/demoChallenge/editorDiv', Record<never, never>, Record<never, never>>,
    '/demoChallenge/ellipsePanel': RouteRecordInfo<'/demoChallenge/ellipsePanel', '/demoChallenge/ellipsePanel', Record<never, never>, Record<never, never>>,
    '/demoChallenge/fileUpload': RouteRecordInfo<'/demoChallenge/fileUpload', '/demoChallenge/fileUpload', Record<never, never>, Record<never, never>>,
    '/demoChallenge/indexedDB': RouteRecordInfo<'/demoChallenge/indexedDB', '/demoChallenge/indexedDB', Record<never, never>, Record<never, never>>,
    '/demoChallenge/intersectionObserver': RouteRecordInfo<'/demoChallenge/intersectionObserver', '/demoChallenge/intersectionObserver', Record<never, never>, Record<never, never>>,
    '/demoChallenge/lens': RouteRecordInfo<'/demoChallenge/lens', '/demoChallenge/lens', Record<never, never>, Record<never, never>>,
    '/demoChallenge/matter': RouteRecordInfo<'/demoChallenge/matter', '/demoChallenge/matter', Record<never, never>, Record<never, never>>,
    '/demoChallenge/minesweeperPage': RouteRecordInfo<'/demoChallenge/minesweeperPage', '/demoChallenge/minesweeperPage', Record<never, never>, Record<never, never>>,
    '/demoChallenge/popoverDemo': RouteRecordInfo<'/demoChallenge/popoverDemo', '/demoChallenge/popoverDemo', Record<never, never>, Record<never, never>>,
    '/demoChallenge/recorder': RouteRecordInfo<'/demoChallenge/recorder', '/demoChallenge/recorder', Record<never, never>, Record<never, never>>,
    '/demoChallenge/renderToString': RouteRecordInfo<'/demoChallenge/renderToString', '/demoChallenge/renderToString', Record<never, never>, Record<never, never>>,
    '/demoChallenge/scope': RouteRecordInfo<'/demoChallenge/scope', '/demoChallenge/scope', Record<never, never>, Record<never, never>>,
    '/demoChallenge/SemanticTags': RouteRecordInfo<'/demoChallenge/SemanticTags', '/demoChallenge/SemanticTags', Record<never, never>, Record<never, never>>,
    '/demoChallenge/svgComponent': RouteRecordInfo<'/demoChallenge/svgComponent', '/demoChallenge/svgComponent', Record<never, never>, Record<never, never>>,
    '/demoChallenge/videojsPlayRemp': RouteRecordInfo<'/demoChallenge/videojsPlayRemp', '/demoChallenge/videojsPlayRemp', Record<never, never>, Record<never, never>>,
    '/demoChallenge/virtualScroll': RouteRecordInfo<'/demoChallenge/virtualScroll', '/demoChallenge/virtualScroll', Record<never, never>, Record<never, never>>,
    '/demoChallenge/watchCarousel': RouteRecordInfo<'/demoChallenge/watchCarousel', '/demoChallenge/watchCarousel', Record<never, never>, Record<never, never>>,
    '/demoChallenge/waterfallFlowa': RouteRecordInfo<'/demoChallenge/waterfallFlowa', '/demoChallenge/waterfallFlowa', Record<never, never>, Record<never, never>>,
    '/demoChallenge/webrtc': RouteRecordInfo<'/demoChallenge/webrtc', '/demoChallenge/webrtc', Record<never, never>, Record<never, never>>,
    '/fileUpload/': RouteRecordInfo<'/fileUpload/', '/fileUpload', Record<never, never>, Record<never, never>>,
    '/flip/flipOne/': RouteRecordInfo<'/flip/flipOne/', '/flip/flipOne', Record<never, never>, Record<never, never>>,
    '/flip/flipTwo/[no]': RouteRecordInfo<'/flip/flipTwo/[no]', '/flip/flipTwo/:no', { no: ParamValue<true> }, { no: ParamValue<false> }>,
    '/hi/[name]': RouteRecordInfo<'/hi/[name]', '/hi/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/keepAlive': RouteRecordInfo<'/keepAlive', '/keepAlive', Record<never, never>, Record<never, never>>,
    '/recorder/': RouteRecordInfo<'/recorder/', '/recorder', Record<never, never>, Record<never, never>>,
    '/three/': RouteRecordInfo<'/three/', '/three', Record<never, never>, Record<never, never>>,
    '/webGL/': RouteRecordInfo<'/webGL/', '/webGL', Record<never, never>, Record<never, never>>,
    '/webGPU/': RouteRecordInfo<'/webGPU/', '/webGPU', Record<never, never>, Record<never, never>>,
  }
}
