/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/blog/': RouteRecordInfo<
      '/blog/',
      '/blog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/': RouteRecordInfo<
      '/demoChallenge/',
      '/demoChallenge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/autoNavBar': RouteRecordInfo<
      '/demoChallenge/autoNavBar',
      '/demoChallenge/autoNavBar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/canvasDrawPage': RouteRecordInfo<
      '/demoChallenge/canvasDrawPage',
      '/demoChallenge/canvasDrawPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/canvasPlum': RouteRecordInfo<
      '/demoChallenge/canvasPlum',
      '/demoChallenge/canvasPlum',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/digitalRain': RouteRecordInfo<
      '/demoChallenge/digitalRain',
      '/demoChallenge/digitalRain',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/DivTable': RouteRecordInfo<
      '/demoChallenge/DivTable',
      '/demoChallenge/DivTable',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/editorDiv': RouteRecordInfo<
      '/demoChallenge/editorDiv',
      '/demoChallenge/editorDiv',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/ellipsePanel': RouteRecordInfo<
      '/demoChallenge/ellipsePanel',
      '/demoChallenge/ellipsePanel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/fileUpload': RouteRecordInfo<
      '/demoChallenge/fileUpload',
      '/demoChallenge/fileUpload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/indexedDB': RouteRecordInfo<
      '/demoChallenge/indexedDB',
      '/demoChallenge/indexedDB',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/intersectionObserver': RouteRecordInfo<
      '/demoChallenge/intersectionObserver',
      '/demoChallenge/intersectionObserver',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/lens': RouteRecordInfo<
      '/demoChallenge/lens',
      '/demoChallenge/lens',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/matter': RouteRecordInfo<
      '/demoChallenge/matter',
      '/demoChallenge/matter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/minesweeperPage': RouteRecordInfo<
      '/demoChallenge/minesweeperPage',
      '/demoChallenge/minesweeperPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/popoverDemo': RouteRecordInfo<
      '/demoChallenge/popoverDemo',
      '/demoChallenge/popoverDemo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/recorder': RouteRecordInfo<
      '/demoChallenge/recorder',
      '/demoChallenge/recorder',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/renderToString': RouteRecordInfo<
      '/demoChallenge/renderToString',
      '/demoChallenge/renderToString',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/scope': RouteRecordInfo<
      '/demoChallenge/scope',
      '/demoChallenge/scope',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/SemanticTags': RouteRecordInfo<
      '/demoChallenge/SemanticTags',
      '/demoChallenge/SemanticTags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/svgComponent': RouteRecordInfo<
      '/demoChallenge/svgComponent',
      '/demoChallenge/svgComponent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/videojsPlayRemp': RouteRecordInfo<
      '/demoChallenge/videojsPlayRemp',
      '/demoChallenge/videojsPlayRemp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/virtualScroll': RouteRecordInfo<
      '/demoChallenge/virtualScroll',
      '/demoChallenge/virtualScroll',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/watchCarousel': RouteRecordInfo<
      '/demoChallenge/watchCarousel',
      '/demoChallenge/watchCarousel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/waterfallFlowa': RouteRecordInfo<
      '/demoChallenge/waterfallFlowa',
      '/demoChallenge/waterfallFlowa',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demoChallenge/webrtc': RouteRecordInfo<
      '/demoChallenge/webrtc',
      '/demoChallenge/webrtc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/fileUpload/': RouteRecordInfo<
      '/fileUpload/',
      '/fileUpload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/flip/flipOne/': RouteRecordInfo<
      '/flip/flipOne/',
      '/flip/flipOne',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/flip/flipTwo/[no]': RouteRecordInfo<
      '/flip/flipTwo/[no]',
      '/flip/flipTwo/:no',
      { no: ParamValue<true> },
      { no: ParamValue<false> },
      | never
    >,
    '/hi/[name]': RouteRecordInfo<
      '/hi/[name]',
      '/hi/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/keepAlive': RouteRecordInfo<
      '/keepAlive',
      '/keepAlive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/recorder/': RouteRecordInfo<
      '/recorder/',
      '/recorder',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/three/': RouteRecordInfo<
      '/three/',
      '/three',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/webGL/': RouteRecordInfo<
      '/webGL/',
      '/webGL',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/webGPU/': RouteRecordInfo<
      '/webGPU/',
      '/webGPU',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/blog/index.vue': {
      routes:
        | '/blog/'
      views:
        | never
    }
    'src/pages/demoChallenge/index.vue': {
      routes:
        | '/demoChallenge/'
      views:
        | never
    }
    'src/pages/demoChallenge/autoNavBar.vue': {
      routes:
        | '/demoChallenge/autoNavBar'
      views:
        | never
    }
    'src/pages/demoChallenge/canvasDrawPage.vue': {
      routes:
        | '/demoChallenge/canvasDrawPage'
      views:
        | never
    }
    'src/pages/demoChallenge/canvasPlum.vue': {
      routes:
        | '/demoChallenge/canvasPlum'
      views:
        | never
    }
    'src/pages/demoChallenge/digitalRain.vue': {
      routes:
        | '/demoChallenge/digitalRain'
      views:
        | never
    }
    'src/pages/demoChallenge/DivTable.vue': {
      routes:
        | '/demoChallenge/DivTable'
      views:
        | never
    }
    'src/pages/demoChallenge/editorDiv.vue': {
      routes:
        | '/demoChallenge/editorDiv'
      views:
        | never
    }
    'src/pages/demoChallenge/ellipsePanel.vue': {
      routes:
        | '/demoChallenge/ellipsePanel'
      views:
        | never
    }
    'src/pages/demoChallenge/fileUpload.vue': {
      routes:
        | '/demoChallenge/fileUpload'
      views:
        | never
    }
    'src/pages/demoChallenge/indexedDB.vue': {
      routes:
        | '/demoChallenge/indexedDB'
      views:
        | never
    }
    'src/pages/demoChallenge/intersectionObserver.vue': {
      routes:
        | '/demoChallenge/intersectionObserver'
      views:
        | never
    }
    'src/pages/demoChallenge/lens.vue': {
      routes:
        | '/demoChallenge/lens'
      views:
        | never
    }
    'src/pages/demoChallenge/matter.vue': {
      routes:
        | '/demoChallenge/matter'
      views:
        | never
    }
    'src/pages/demoChallenge/minesweeperPage.vue': {
      routes:
        | '/demoChallenge/minesweeperPage'
      views:
        | never
    }
    'src/pages/demoChallenge/popoverDemo.vue': {
      routes:
        | '/demoChallenge/popoverDemo'
      views:
        | never
    }
    'src/pages/demoChallenge/recorder.vue': {
      routes:
        | '/demoChallenge/recorder'
      views:
        | never
    }
    'src/pages/demoChallenge/renderToString.vue': {
      routes:
        | '/demoChallenge/renderToString'
      views:
        | never
    }
    'src/pages/demoChallenge/scope.vue': {
      routes:
        | '/demoChallenge/scope'
      views:
        | never
    }
    'src/pages/demoChallenge/SemanticTags.vue': {
      routes:
        | '/demoChallenge/SemanticTags'
      views:
        | never
    }
    'src/pages/demoChallenge/svgComponent.vue': {
      routes:
        | '/demoChallenge/svgComponent'
      views:
        | never
    }
    'src/pages/demoChallenge/videojsPlayRemp.vue': {
      routes:
        | '/demoChallenge/videojsPlayRemp'
      views:
        | never
    }
    'src/pages/demoChallenge/virtualScroll.vue': {
      routes:
        | '/demoChallenge/virtualScroll'
      views:
        | never
    }
    'src/pages/demoChallenge/watchCarousel.vue': {
      routes:
        | '/demoChallenge/watchCarousel'
      views:
        | never
    }
    'src/pages/demoChallenge/waterfallFlowa.vue': {
      routes:
        | '/demoChallenge/waterfallFlowa'
      views:
        | never
    }
    'src/pages/demoChallenge/webrtc.vue': {
      routes:
        | '/demoChallenge/webrtc'
      views:
        | never
    }
    'src/pages/fileUpload/index.vue': {
      routes:
        | '/fileUpload/'
      views:
        | never
    }
    'src/pages/flip/flipOne/index.vue': {
      routes:
        | '/flip/flipOne/'
      views:
        | never
    }
    'src/pages/flip/flipTwo/[no].vue': {
      routes:
        | '/flip/flipTwo/[no]'
      views:
        | never
    }
    'src/pages/hi/[name].vue': {
      routes:
        | '/hi/[name]'
      views:
        | never
    }
    'src/pages/keepAlive.vue': {
      routes:
        | '/keepAlive'
      views:
        | never
    }
    'src/pages/recorder/index.vue': {
      routes:
        | '/recorder/'
      views:
        | never
    }
    'src/pages/three/index.vue': {
      routes:
        | '/three/'
      views:
        | never
    }
    'src/pages/webGL/index.vue': {
      routes:
        | '/webGL/'
      views:
        | never
    }
    'src/pages/webGPU/index.vue': {
      routes:
        | '/webGPU/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
