/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Astralbackground: typeof import('./src/components/Astralbackground/index.vue')['default']
    AsyncComponent: typeof import('./src/components/AsyncComponent.vue')['default']
    Basic: typeof import('./src/components/ssrComponents/basic.vue')['default']
    CanvasDraw: typeof import('./src/components/CanvasDraw/index.vue')['default']
    CanvasTool: typeof import('./src/components/CanvasDraw/CanvasTool.vue')['default']
    Carousel: typeof import('./src/components/Carousel/index.vue')['default']
    CarouselDot: typeof import('./src/components/Carousel/CarouselDot.vue')['default']
    CarouselItem: typeof import('./src/components/Carousel/CarouselItem.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    CssVirtualList: typeof import('./src/components/VirtualList/CssVirtualList.vue')['default']
    DemochallengeList: typeof import('./src/components/DemochallengeList/index.vue')['default']
    Drag: typeof import('./src/components/Drag/index.vue')['default']
    Fireworks: typeof import('./src/components/Fireworks/index.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    InputAnimate: typeof import('./src/components/InputAnimate/index.vue')['default']
    MineBlock: typeof import('./src/components/Minesweeper/MineBlock.vue')['default']
    Minesweeper: typeof import('./src/components/Minesweeper/index.vue')['default']
    Modal: typeof import('./src/components/Modal/index.vue')['default']
    Overlayer: typeof import('./src/components/Overlayer/index.vue')['default']
    Popover: typeof import('./src/components/Popover/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('./src/components/Starport/starport.vue')['default']
    StarportCarrier: typeof import('./src/components/Starport/starportCarrier.vue')['default']
    StarportCraft: typeof import('./src/components/Starport/starportCraft.vue')['default']
    TheImage: typeof import('./src/components/Starport/TheImage.vue')['default']
    VirtualList: typeof import('./src/components/VirtualList/index.vue')['default']
    VirtualListItem: typeof import('./src/components/VirtualList/VirtualListItem.vue')['default']
    WaterfallFlow: typeof import('./src/components/WaterfallFlow/index.vue')['default']
  }
}
