// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsyncComponent: typeof import('./src/components/AsyncComponent.vue')['default']
    Basic: typeof import('./src/components/ssrComponents/Basic.vue')['default']
    Carousel: typeof import('./src/components/Carousel/index.vue')['default']
    CarouselDot: typeof import('./src/components/Carousel/CarouselDot.vue')['default']
    CarouselItem: typeof import('./src/components/Carousel/CarouselItem.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Fireworks: typeof import('./src/components/Fireworks.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Modal: typeof import('./src/components/Modal/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheImage: typeof import('./src/components/starPort/TheImage.vue')['default']
  }
}
